services:
  scheduling-service:
    build:
      context: ./backend/scheduling-service
      dockerfile: Dockerfile
    container_name: scheduling-service-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/scheduling_service?schema=public
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      RABBITMQ_EXCHANGE: scheduling.events
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  tenant-service:
    build:
      context: ./backend/tenant-service
      dockerfile: Dockerfile
    container_name: tenant-service-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/tenant_service?schema=public
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      RABBITMQ_EXCHANGE: clinica.topic
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - app-network

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth-service-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3004
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/auth_service?schema=public
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      REDIS_URL: redis://redis:6379
      JWT_SECRET: secret
    ports:
      - "3004:3004"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge